name: Sync to Backend Repo

on:
  push:
    branches:
      - main

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Git Sync to Destination
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'https://github.com/enovosoft/protigga.git'
          source_branch: 'main'
          destination_repo: 'https://github.com/pioneerAlpha/protigga-backend-nodejs.git'
          destination_branch: 'main' # Destination-এর ব্রাঞ্চ
          github_token: ${{ secrets.DESTINATION_REPO_PAT }}
