name: Sync to PioneerAlpha

on:
  push:
    branches:
      - main

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to PioneerAlpha
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://github.com/pioneerAlpha/protigga-backend-nodejs.git'
          GIT_USERNAME: '${{ github.actor }}' # এটা অটোমেটিক আপনার ইউজারনেম নিয়ে নেবে
          GIT_PASSWORD: ${{ secrets.API_TOKEN_GITHUB }}
          PUSH_ALL_REFS: false
          git_push_args: '--force'
